config-version: 1

# The root folder for the database change scripts
root-folder: '.'

# The name of the snowflake account
snowflake-account: 'gmxgmpx-rb43905'

# The name of the snowflake user
snowflake-user: 'MANIKUMAR'

# The name of the default role to use
snowflake-role: 'ACCOUNTADMIN'

# The name of the default warehouse to use
snowflake-warehouse: 'COMPUTE_WH'

# The name of the default database to use
snowflake-database: 'METADATA'

# The name of the default schema to use
snowflake-schema: 'PUBLIC'

# The name of the default change history table
change-history-table: 'METADATA.SCHEMACHANGE.CHANGE_HISTORY'

# Define values for the variables to replace in change scripts
vars:
  var1: 'value1'
  var2: 'value2'
  secrets:
    var3: 'value3' # This is considered a secret and will not be displayed in any output

# Create the change history schema and table, if they do not exist
create-change-history-table: true

# Enable autocommit feature for DML commands
autocommit: false

# Display verbose debugging details during execution
verbose: false

# Run schemachange in dry run mode
dry-run: false

# A string to include in the QUERY_TAG that is attached to every SQL statement executed
query-tag: 'QUERY_TAG'

# Information for OAuth token requests
oauthconfig:
  # URL where token requests are posted to
  token-provider-url: 'https://login.microsoftonline.com/{{ env_var('AZURE_ORG_GUID', 'default') }}/oauth2/v2.0/token'
  # Name of JSON entity returned by request
  token-response-name: 'access_token'
  # Headers needed for successful post or other security markings
  token-request-headers:
    Content-Type: "application/x-www-form-urlencoded"
    User-Agent: "python/schemachange"
  # Request payload for Token
  token-request-payload:
    client_id: '{{ env_var('CLIENT_ID', 'default') }}'
    username: '{{ env_var('USER_ID', 'default') }}'
    password: '{{ env_var('USER_PASSWORD', 'default') }}'
    grant_type: 'password'
    scope: '{{ env_var('SESSION_SCOPE', 'default') }}'
